### PR TITLE
[master] mac

### PR DESCRIPTION
**Pull request by bartcubbins**

### CODE REVIEW

**Comment by jerpelea** [comment]
please fix the second commit

**Comment by bartcubbins** [comment]
@jerpelea Kanuti uses the prima wlan driver and the path is valid for k3.18+

**Comment by jerpelea** [comment]
check tge whitespaces and the new line 😉

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-kanuti/pull/221/commits/074ea8fd297acaec712665071744c12d19870790

**Comment by bartcubbins** [comment]
@jerpelea haha, sorry, give me a minute :)

**Comment by bartcubbins** [comment]
@jerpelea wait a second, maybe I need some rest.. but as far as I can see, everything is fine😅
https://github.com/bartcubbins/device-sony-kanuti/blob/master-mac/platform.mk#L132-L134

**Comment by jerpelea** [comment]
in the web diff I see a new line

**Comment by bartcubbins** [comment]
please take a look again:)
https://imgur.com/a/Q2vV9

**Comment by jerpelea** [comment]
it appears to be a rendering issue

**Comment by bartcubbins** [comment]
Most likely, last time github gets many changes

**Pull request merged**
