### PR TITLE
kanuti: Introduce IS_8GB_KANUTI and IS_16GB_KANUTI variables

### PR DESCRIPTION
**Pull request by pablomh**
It will set the correct size for BOARD_USERDATAIMAGE_PARTITION_SIZE for 16 GB
devices

### CODE REVIEW

**Comment by pablomh** [comment]
Needs to be pushed after https://github.com/sonyxperiadev/device-sony-tulip/pull/28 to avoid to have the variables not defined.

**Comment by bartcubbins** [comment]
I think that it is possible to simplify this

**Comment by pablomh** [comment]
From what I've seen, the inheritance makes it difficult to workaround.

**Comment by pablomh** [comment]
Needs more work :/

**Comment by alviteri** [comment]
https://github.com/sonyxperiadev/device-sony-tulip/pull/32

**Pull request closed without merging**
