### PR TITLE
kanuti: Enable init_sony

### PR DESCRIPTION
**Pull request by artem**
According to recent build tree changes

### CODE REVIEW

**Comment by jerpelea** [comment]
kanuti should use the same "fix" as loire

**Comment by bartcubbins** [comment]
@jerpelea which one?

**Comment by bartcubbins** [comment]
@jerpelea which one?

**Comment by bartcubbins** [comment]
@jerpelea I'm not sure that we can use this: https://github.com/sonyxperiadev/kernel/commit/856be0fc8d08c00aa2a892698d4b78229ea6c0bb with old bootloader

**Comment by jerpelea** [comment]
it should work 
check it

**Pull request closed without merging**
