### PR TITLE
kanuti: Set WITH_DEXPREOPT_BOOT_IMG_ONLY:=true

### PR DESCRIPTION
**Pull request by pablomh**
To cope with shortage in space in system partition

### CODE REVIEW

**Comment by jerpelea** [comment]
we already use 
DONT_DEXPREOPT_PREBUILTS := true
and this should save enough space for tulip

https://github.com/sonyxperiadev/device-sony-common/blob/master/CommonConfig.mk#L83

**Comment by pablomh** [comment]
It wasn't enough after adding libfuse and exfat related packages so I had to add this (only to kanuti as it seems it's the only platform so constrained).

**Comment by jerpelea** [comment]
please do a clean build without any change to AOSP
and run 
adb shell df
to check how much space you have

**Comment by pablomh** [comment]
You're completely right. I should have modified it locally before you commited your fix and that's why I didn't notice:

```
$ adb shell df
Filesystem                             1K-blocks    Used Available Use% Mounted on
tmpfs                                     950872     444    950428   1% /dev
tmpfs                                     950872       0    950872   0% /mnt
tmpfs                                     950872       0    950872   0% /tmp
/dev/block/bootdevice/by-name/system     2531076 1616160    898532  65% /system
/dev/block/bootdevice/by-name/userdata  11609304 2827476   8765444  25% /data
/dev/block/bootdevice/by-name/cache       197472   15940    177436   9% /cache
/dev/block/bootdevice/by-name/modem        65488   49168     16320  76% /firmware
/data/media                             11609304 2827476   8765444  25% /storage/emulated
```

**Pull request closed without merging**
