### PR TITLE
kanuti: Graphics Updates for Nougat

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri davidteri91@gmail.com

### CODE REVIEW

**Comment by pablomh** [comment]
Any way to test this?

**Comment by jerpelea** [comment]
you can not test them unless you have new adreno

**Comment by pablomh** [comment]
OK, I will wait until then :)

**Comment by alviteri** [comment]
@pablomh you can test this extracting the needed stuff (adreno-vulkan) from angler

**Pull request closed without merging**
